using DSR.SlotDetailsDefinition;

namespace DSR.SlotDetails.InventoryDetails.Items;

public enum ItemType
{
    UNKNOWN,

    // Key Items
    PeculiarDoll,
    LargeEmber,
    VeryLargeEmber,
    CrystalEmber,
    LargeMagicEmber,
    EnchantedEmber,
    DivineEmber,
    LargeDivineEmber,
    DarkEmber,
    LargeFlameEmber,
    ChaosFlameEmber,
    BasementKey,
    CrestOfArtorias,
    CageKey,
    ArchiveTowerCellKey,
    ArchiveTowerGiantDoorKey,
    ArchiveTowerGiantCellKey,
    BlighttownKey,
    KeyToNewLondoRuins,
    AnnexKey,
    DungeonCellKey,
    BigPilgrimsKey,
    UndeadAsylumF2EastKey,
    KeyToTheSeal,
    KeyToDepths,
    LiftChamberKey, // Unoptainable
    UndeadAsylumF2WestKey,
    MysteryKey,
    SewerChamberKey,
    WatchtowerBasementKey,
    ArchivePrisonExtraKey,
    ResidenceKey,
    MasterKey,
    LordSoulGravelordNito,
    LordSoulBedOfChaos,
    BequeathedLordSoulShardFourKings,
    BequeathedLordSoulShardSeathTheScaleless,
    Lordvessel,
    WeaponSmithbox,
    ArmorSmithbox,
    Repairbox,
    RiteOfKindling,
    BottomlessBox,


    // Armor
    // Empty Slots
    Helm,
    Chest,
    Gauntlets,
    Leggings,

    CatarinaHelm,
    CatarinaArmor,
    CatarinaGauntlets,
    CatarinaLeggings,

    PaladinHelm,
    PaladinArmor,
    PaladinGauntlets,
    PaladinLeggings,

    DarkMask,
    DarkArmor,
    DarkGauntlets,
    DarkLeggings,

    BrigandHood,
    BrigandArmor,
    BrigandGauntlets,
    BrigandTrousers,

    ShadowMask,
    ShadowGarb,
    ShadowGauntlets,
    ShadowLeggings,

    BlackIronHelm,
    BlackIronArmor,
    BlackIronGauntlets,
    BlackIronLeggings,

    SmoughsHelm,
    SmoughsArmor,
    SmoughsGauntlets,
    SmoughsLeggings,

    SixEyedHelmOfTheChannelers,
    RobeOfTheChannelers,
    GauntletsOfTheChannelers,
    WaistclothOfTheChannelers,

    HelmOfFavor,
    EmbracedArmorOfFavor,
    GauntletsOfFavor,
    LeggingsOfFavor,

    HelmOfTheWise,
    ArmorOfTheGlorious,
    GauntletsOfTheVanquisher,
    BootsOfTheExplorer,

    StoneHelm,
    StoneArmor,
    StoneGauntlets,
    StoneLeggings,

    CrystallineHelm,
    CrystallineArmor,
    CrystallineGauntlets,
    CrystallineLeggings,

    MaskOfTheSealer,
    CrimsonRobe,
    CrimsonGloves,
    CrimsonWaistcloth,

    MaskOfVelka,
    BlackClericRobe,
    BlackManchette,
    BlackTights,

    IronHelm,
    ArmorOfTheSun,
    IronBracelet,
    IronLeggings,

    ChainHelm,
    ChainArmor,
    LeatherGauntlets,
    ChainLeggings,

    ClericHelm,
    ClericArmor,
    ClericGauntlets,
    ClericLeggings,

    SunlightMaggot,

    HelmOfThorns,
    ArmorOfThorns,
    GauntletsOfThorns,
    LeggingsOfThorns,

    StandardHelm,
    HardLeatherArmor,
    HardLeatherGauntlets,
    HardLeatherBoots,

    SorcererHat,
    SorcererCloak,
    SorcererGauntlets,
    SorcererBoots,

    TatteredClothHood,
    TatteredClothRobe,
    TatteredClothManchette,
    HeavyBoots,

    PharisHat,
    LeatherArmor,
    LeatherGloves,
    LeatherBoots,

    PaintingGuardianHood,
    PaintingGuardianRobe,
    PaintingGuardianGloves,
    PaintingGuardianWaistcloth,

    OrnsteinsHelm,
    OrnsteinsArmor,
    OrnsteinsGauntlets,
    OrnsteinsLeggings,

    EasternHelm,
    EasternArmor,
    EasternGauntlets,
    EasternLeggings,

    XanthousCrown,
    XanthousOvercoat,
    XanthousGloves,
    XanthousWaistcloth,

    ThiefMask,
    BlackLeatherArmor,
    BlackLeatherGloves,
    BlackLeatherBoots,

    PriestsHat,
    HolyRobe,
    TravelingGlovesCleric,
    HolyTrousers,

    BlackKnightHelm,
    BlackKnightArmor,
    BlackKnightGauntlets,
    BlackKnightLeggings,

    CrownOfDusk,
    AntiquatedDress,
    AntiquatedGloves,
    AntiquatedSkirt,

    WitchHat,
    WitchCloak,
    WitchGloves,
    WitchSkirt,

    EliteKnightHelm,
    EliteKnightArmor,
    EliteKnightGauntlets,
    EliteKnightLeggings,

    WandererHood,
    WandererCoat,
    WandererManchette,
    WandererBoots,

    MageSmithHat,       // Unoptainable
    MageSmithCoat,      // Unoptainable
    MageSmithGauntlets, // Unoptainable
    MageSmithBoots,     // Unoptainable

    BigHat,
    SageRobe,
    TravelingGlovesBigHat,
    TravelingBoots,

    KnightHelm,
    KnightArmor,
    KnightGauntlets,
    KnightLeggings,

    DingyHood,
    DingyRobe,
    DingyGloves,
    BloodStainedSkirt,

    MaidenHood,
    MaidenBody,
    MaidenGloves,
    MaidenSkirt,

    SilverKnightHelm,
    SilverKnightArmor,
    SilverKnightGauntlets,
    SilverKnightLeggings,

    HavelsHelm,
    HavelsArmor,
    HavelsGauntlets,
    HavelsLeggings,

    BrassHelm,
    BrassArmor,
    BrassGauntlets,
    BrassLeggings,

    GoldHemmedBlackHood,
    GoldHemmedBlackCloak,
    GoldHemmedBlackGloves,
    GoldHemmedBlackSkirt,

    GolemHelm,
    GolemArmor,
    GolemGauntlets,
    GolemLeggings,

    HollowSoldierHelm,
    HollowSoldierArmor,
    HollowSoldierWaistcloth,

    SteelHelm,
    SteelArmor,
    SteelGauntlets,
    SteelLeggings,

    HollowThiefsHood,
    HollowThiefsLeatherArmor,
    HollowThiefsTights,

    BalderHelm,
    BalderArmor,
    BalderGauntlets,
    BalderLeggings,

    HollowWarriorHelm,
    HollowWarriorArmor,
    HollowWarriorWaistcloth,

    GiantHelm,
    GiantArmor,
    GiantGauntlets,
    GiantLeggings,

    CrownOfTheDarkSun,
    MoonlightRobe,
    MoonlightGloves,
    MoonlightWaistcloth,

    CrownOfTheGreatLord,
    RobeOfTheGreatLord,
    BraceletOfTheGreatLord,
    AnkletOfTheGreatLord,

    Sack,
    SymbolOfAvarice,
    RoyalHelm,
    MaskOfTheFather,
    MaskOfTheMother,
    MaskOfTheChild,
    FangBoarHelm,
    GargoyleHelm,

    BlackSorcererHat,
    BlackSorcererCloak,
    BlackSorcererGauntlets,
    BlackSorcererBoots,

    EliteClericHelm,        // Unoptainable
    EliteClericArmor,       // Unoptainable
    EliteClericGauntlets,   // Unoptainable
    EliteClericLeggings,    // Unoptainable


    // Weapons
    // Empty Slot
    Fists,

    // Daggers
    Dagger,
    ParryingDagger,
    GhostBlade,
    BanditsKnife,
    PriscillasDagger,

    // Straight Swords
    Shortsword,
    Longsword,
    Broadsword,
    BrokenStraightSword,
    BalderSideSword,
    CrystalStraightSword,
    SunlightStraightSword,
    BarbedStraightSword,
    SilverKnightStraightSword,
    AstorasStraightSword,
    DarkSword,
    DrakeSword,
    StraightSwordHilt,

    // Greatswords
    BastardSword,
    Claymore,
    ManserpentGreatsword,
    Flamberge,
    CrystalGreatsword,
    StoneGreatsword,

    // TODO
    GreatswordOfArtoriasBrokenStraightSword,
    GreatswordOfArtoriasStraightSwordHilt,
    MoonlightGreatsword,
    BlackKnightSword,

    // TODO
    GreatswordOfArtoriasCursedDagger,
    GreatswordOfArtoriasCursedParryingDagger,
    GreatswordOfArtoriasCursedBanditsKnife,
    GreatswordOfArtoriasCursedShortSword,
    GreatswordOfArtoriasCursedLongSword,
    GreatswordOfArtoriasCursedBroadSword,
    GreatswordOfArtoriasCursedBalderSideSword,
    GreatswordOfArtoriasCursedSunlightStraightSword,
    GreatswordOfArtoriasCursedBarbedStraightSword,
    GreatswordOfArtoriasCursedDarkSword,
    GreatswordOfArtoriasCursedBastardSword,
    GreatswordOfArtoriasCursedClaymore,
    GreatswordOfArtoriasCursedManserpentGreatsword,
    GreatswordOfArtoriasCursedFlamberge,
    GreatswordOfArtoriasCursedZweihander,
    GreatswordOfArtoriasCursedGreatsword,
    GreatswordOfArtoriasCursedDemonGreatMachete,
    GreatLordGreatswordDagger,
    GreatLordGreatswordParryingDagger,
    GreatLordGreatswordBanditsKnife,
    GreatLordGreatswordShortSword,
    GreatLordGreatswordLongSword,
    GreatLordGreatswordBroadSword,
    GreatLordGreatswordBalderSideSword,
    GreatLordGreatswordSunlightStraightSword,
    GreatLordGreatswordBarbedStraightSword,
    GreatLordGreatswordDarkSword,
    GreatLordGreatswordBastardSword,
    GreatLordGreatswordClaymore,
    GreatLordGreatswordManserpentGreatsword,
    GreatLordGreatswordFlamberge,
    GreatLordGreatswordZweihander,
    GreatLordGreatswordGreatsword,
    GreatLordGreatswordDemonGreatMachete,

    // Ultra Greatswords
    Zweihander,
    Greatsword,
    DemonGreatMachete,
    DragonGreatsword,
    BlackKnightGreatsword,

    // Curved Swords
    Scimitar,
    Falchion,
    Shotel,
    JaggedGhostBlade,
    PaintingGuardianSword,
    QuelaagsFuryswordScimitar,
    QuelaagsFuryswordFalchion,
    QuelaagsFuryswordShotel,
    QuelaagsFuryswordPaintingGuardianSword,
    QuelaagsFuryswordServer,
    QuelaagsFuryswordMurakumo,

    // Curved Greatswords
    Server,
    Murakumo,
    GravelordSword,

    // Katanas
    Uchigatana,
    WashingPole,
    Iaito,
    ChaosBladeUchigatana,
    ChaosBladeWashingPole,
    ChaosBladeIaito,

    // Piercing Swords
    MailBreaker,
    Rapier,
    Estoc,
    VelkasRapier,
    RicardsRapier,

    // Axes
    HandAxe,
    BattleAxe,
    CrescentAxe,
    ButcherKnife,
    GolemAxeHandAxe,
    GolemAxeBattleAxe,
    GolemAxeButcherKnife,
    GolemAxeGargoyleTailAxe,
    GolemAxeDemonsGreataxe,
    GargoyleTailAxe,

    // Greataxes
    Greataxe,
    DemonsGreataxe,
    DragonKingGreataxe,
    BlackKnightGreataxe,

    // Hammers
    Club,
    Mace,
    MorningStar,
    Warpick,
    Pickaxe,
    ReinforcedClub,
    BlacksmithHammer,
    BlacksmithGiantHammer,
    HammerOfVamos,

    // Great Hammers
    GreatClub,
    Grant,
    DemonsGreatHammer,
    DragonTooth,
    LargeClub,
    SmoughsHammerClub,
    SmoughsHammerMace,
    SmoughsHammerMorningStar,
    SmoughsHammerWarpick,
    SmoughsHammerPickaxe,
    SmoughsHammerReinforcedClub,
    SmoughsHammerBlacksmithHammer,
    SmoughsHammerGreatClub,
    SmoughsHammerDemonsGreatHammer,
    SmoughsHammerLargeClub,

    // Fist Weapons
    Caestus,
    Claw,
    DragonBoneFistCaestus,
    DragonBoneFistClaw,
    DarkHand,

    // Spears
    Spear,
    WingedSpear,
    Partizan,
    DemonsSpear,
    ChannelersTrident,
    SilverKnightSpear,
    Pike,
    DragonslayerSpearMailBreaker,
    DragonslayerSpearRapier,
    DragonslayerSpearEstoc,
    DragonslayerSpearRicardsRapier,
    DragonslayerSpearSpear,
    DragonslayerSpearWingedSpear,
    DragonslayerSpearPartizan,
    DragonslayerSpearPike,
    MoonlightButterflyHornMailBreaker,
    MoonlightButterflyHornRapier,
    MoonlightButterflyHornEstoc,
    MoonlightButterflyHornRicardsRapier,
    MoonlightButterflyHornSpear,
    MoonlightButterflyHornWingedSpear,
    MoonlightButterflyHornPartizan,
    MoonlightButterflyHornPike,

    // Halberds
    Halberd,
    GiantsHalberd,
    TitaniteCatchPole,
    GargoylesHalberd,
    BlackKnightHalberd,
    Lucerne,
    Scythe,
    GreatScythe,
    LifehuntScytheHalberd,
    LifehuntScytheGargoylesHalberd,
    LifehuntScytheLucerne,
    LifehuntScytheScythe,
    LifehuntScytheGreatScythe,
    LifehuntScytheWhip,
    LifehuntScytheNotchedWhip,

    // Bows
    ShortBow,
    LongBow,
    BlackBowOfPharis,
    DragonslayerGreatbow,
    CompositeBow,
    DarkmoonBowShortBow,
    DarkmoonBowLongBow,
    DarkmoonBowBlackBowOfPharis,
    DarkmoonBowCompositeBow,

    // Crossbows
    LightCrossbow,
    HeavyCrossbow,
    Avelyn,
    SniperCrossbow,

    // Catalysts
    SorcerersCatalyst,
    BeatricesCatalyst,
    TinBanishmentCatalyst,
    LogansCatalyst,
    TinDarkmoonCatalystSorcerersCatalyst,
    TinDarkmoonCatalystBeatricesCatalyst,
    TinDarkmoonCatalystTinBanishmentCatalyst,
    TinDarkmoonCatalystLogansCatalyst,
    TinDarkmoonCatalystOolacileIvoryCatalyst,
    OolacileIvoryCatalyst,
    TinCrystallizationCatalyst,
    DemonsCatalyst,
    IzalithCatalyst,

    // Pyromancy Flames
    PyromancyFlame,
    PyromancyFlameAscended,

    // Talismans
    Talisman,
    CanvasTalisman,
    ThorolundTalisman,
    IvoryTalisman,
    SunlightTalisman,
    DarkmoonTalisman,
    VelkasTalisman,

    SkullLantern,

    // Whips
    Whip,
    NotchedWhip,


    // Shields
    // Standard Shields
    EastWestShield,
    WoodenShield,
    LargeLeatherShield,
    SmallLeatherShield,
    TargetShield,
    Buckler,
    CrackedRoundShield,
    LeatherShield,
    PlankShield,
    CaduceusRoundShield,
    CrystalRingShieldEastWestShield,
    CrystalRingShieldWoodenShield,
    CrystalRingShieldLargeLeatherShield,
    CrystalRingShieldSmallLeatherShield,
    CrystalRingShieldTargetShield,
    CrystalRingShieldBuckler,
    CrystalRingShieldCrackedRoundShield,
    CrystalRingShieldLeatherShield,
    CrystalRingShieldPlankShield,
    CrystalRingShieldCaduceusRoundShield,
    CrystalRingShieldHeaterShield,
    CrystalRingShieldKnightShield,
    CrystalRingShieldTowerKiteShield,
    CrystalRingShieldGrassCrestShield,
    CrystalRingShieldHollowSoldierShield,
    CrystalRingShieldBalderShield,
    CrystalRingShieldWarriorsRoundShield,
    CrystalRingShieldIronRoundShield,
    CrystalRingShieldSpiderShield,
    CrystalRingShieldSpikedShield,
    CrystalRingShieldSunlightShield,
    CrystalRingShieldPierceShield,
    CrystalRingShieldRedandWhiteRoundShield,
    CrystalRingShieldCaduceusKiteShield,
    CrystalRingShieldGargoylesShield,
    CrystalRingShieldEagleShield,
    CrystalRingShieldTowerShield,
    CrystalRingShieldGiantShield,
    CrystalRingShieldBonewheelShield,
    CrystalRingShieldEffigyShield,
    CrystalRingShieldSanctus,
    CrystalRingShieldBloodshield,
    CrystalRingShieldBlackIronGreatshield,
    
    // Standard Shields
    HeaterShield,
    KnightShield,
    TowerKiteShield,
    GrassCrestShield,
    HollowSoldierShield,
    BalderShield,
    CrestShield,
    DragonCrestShield,
    WarriorsRoundShield,
    IronRoundShield,
    SpiderShield,
    SpikedShield,
    CrystalShield,
    SunlightShield,
    SilverKnightShield,
    BlackKnightShield,
    PierceShield,
    RedandWhiteRoundShield,
    CaduceusKiteShield,
    GargoylesShield,
    
    // Greatshields
    EagleShield,
    TowerShield,
    GiantShield,
    StoneGreatshield,
    HavelsGreatshield,
    BonewheelShield,
    GreatshieldOfArtoriasEastWestShield,
    GreatshieldOfArtoriasWoodenShield,
    GreatshieldOfArtoriasLargeLeatherShield,
    GreatshieldOfArtoriasSmallLeatherShield,
    GreatshieldOfArtoriasTargetShield,
    GreatshieldOfArtoriasBuckler,
    GreatshieldOfArtoriasCrackedRoundShield,
    GreatshieldOfArtoriasLeatherShield,
    GreatshieldOfArtoriasPlankShield,
    GreatshieldOfArtoriasCaduceusRoundShield,
    GreatshieldOfArtoriasHeaterShield,
    GreatshieldOfArtoriasKnightShield,
    GreatshieldOfArtoriasTowerKiteShield,
    GreatshieldOfArtoriasGrassCrestShield,
    GreatshieldOfArtoriasHollowSoldierShield,
    GreatshieldOfArtoriasBalderShield,
    GreatshieldOfArtoriasWarriorsRoundShield,
    GreatshieldOfArtoriasIronRoundShield,
    GreatshieldOfArtoriasSpiderShield,
    GreatshieldOfArtoriasSpikedShield,
    GreatshieldOfArtoriasSunlightShield,
    GreatshieldOfArtoriasPierceShield,
    GreatshieldOfArtoriasRedandWhiteRoundShield,
    GreatshieldOfArtoriasCaduceusKiteShield,
    GreatshieldOfArtoriasGargoylesShield,
    GreatshieldOfArtoriasEagleShield,
    GreatshieldOfArtoriasTowerShield,
    GreatshieldOfArtoriasGiantShield,
    GreatshieldOfArtoriasBonewheelShield,
    GreatshieldOfArtoriasEffigyShield,
    GreatshieldOfArtoriasSanctus,
    GreatshieldOfArtoriasBloodshield,
    GreatshieldOfArtoriasBlackIronGreatshield,
    EffigyShield,
    Sanctus,
    Bloodshield,
    BlackIronGreatshield,
    

    // Ammunition
    // Arrows
    StandardArrow,
    LargeArrow,
    FeatherArrow,
    FireArrow,
    PoisonArrow,
    MoonlightArrow,
    WoodenArrow,
    DragonslayerArrow,
    
    // Bolts
    StandardBolt,
    HeavyBolt,
    SniperBolt,
    WoodBolt,
    LightningBolt,

    
    // Rings
    HavelsRing,
    RedTearstoneRing,
    DarkmoonBladeCovenantRing,
    CatCovenantRing,
    CloranthyRing,
    FlameStoneplateRing,
    ThunderStoneplateRing,
    SpellStoneplateRing,
    SpeckledStoneplateRing,
    BloodbiteRing,
    PoisonbiteRing,
    TinyBeingsRing,
    CursebiteRing,
    WhiteSeanceRing,
    BellowingDragoncrestRing,
    DuskCrownRing,
    HornetRing,
    HawkRing,
    RingOfSteelProtection,
    CovetousGoldSerpentRing,
    CovetousSilverSerpentRing,
    SlumberingDragoncrestRing,
    RingOfFog,
    RustedIronRing,
    RingOfSacrifice,
    RareRingOfSacrifice,
    DarkWoodGrainRing,
    RingOfTheSunPrincess,
    OldWitchsRing,
    CovenantOfArtorias,
    OrangeCharredRing,
    LingeringDragoncrestRing,
    RingOfTheEvilEye,
    RingOfFavorandProtection,
    LeoRing,
    EastWoodGrainRing,
    WolfRing,
    BlueTearstoneRing,
    RingOfTheSunsFirstborn,
    DarkmoonSeanceRing,


    // Items
    WhiteSignSoapstone,
    RedSignSoapstone,
    RedEyeOrb,
    BlackSeparationCrystal,
    OrangeGuidanceSoapstone,
    BookOfTheGuilty,
    EyeOfDeath,
    CrackedRedEyeOrb,
    ServantRoster,
    BlueEyeOrb,
    DragonEye,
    BlackEyeOrb,
    BlackEyeOrbShiva,       // Unoptainable
    Darksign,
    EstusFlask,
    DivineBlessing,
    GreenBlossom,
    BloodredMossClump,
    PurpleMossClump,
    BloomingPurpleMossClump,
    PurgingStone,
    EggVermifluge,
    RepairPowder,
    ThrowingKnife,
    PoisonThrowingKnife,
    Firebomb,
    DungPie,
    AlluringSkull,
    LloydsTalisman,
    BlackFirebomb,
    CharcoalPineResin,
    GoldPineResin,
    TransientCurse,
    RottenPineResin,
    HomewardBone,
    PrismStone,
    Binoculars,
    Indictment,
    SouvenirOfReprisal,
    SunlightMedal,
    Pendant,
    DragonHeadStone,
    DragonTorsoStone,
    Rubbish,
    CopperCoin,
    SilverCoin,
    GoldCoin,
    DriedFinger,
    FireKeeperSoulAnastaciaOfAstora,
    FireKeeperSoulDarkmoonKnightess,
    FireKeeperSoulQuelaagsSister,
    FireKeeperSoulNewLondoRuins,
    FireKeeperSoulBlighttown,
    FireKeeperSoulTheDukesArchives,
    FireKeeperSoulUndeadParish,
    SoulOfALostUndead,
    LargeSoulOfALostUndead,
    SoulOfANamelessSoldier,
    LargeSoulOfANamelessSoldier,
    SoulOfAProudKnight,
    LargeSoulOfAProudKnight,
    SoulOfABraveWarrior,
    LargeSoulOfABraveWarrior,
    SoulOfAHero,
    SoulOfAGreatHero,
    Humanity,
    TwinHumanity,
    SoulOfQuelaag,
    SoulOfSif,
    SoulOfGwyn,
    CoreOfAnIronGolem,
    SoulOfOrnstein,
    SoulOfTheMoonlightButterfly,
    SoulOfSmough,
    SoulOfPriscilla,
    SoulOfGwyndolin,
    

    TitaniteShard,
    TitaniteChunk,
    TwinklingTitanite,

    // Spells
    SoulArrow,
    HeavySoulArrow,
}